<a href="https://colab.research.google.com/github/AaronTYT/IOD_lab1/blob/main/IOD_Lab-1.2.1%20Vector_Matrix%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

In this lab you will use Python (with the NumPy library) to carry out linear algebra operations.

1. Compute the scalar product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number.

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [3]:
import numpy as np

from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/drive/MyDrive/IOD_Data/Employee-attrition.csv')
print(df.head())

   EmployeeID   recorddate_key birthdate_key orighiredate_key  \
0        1318  12/31/2006 0:00      1/3/1954        8/28/1989   
1        1318  12/31/2007 0:00      1/3/1954        8/28/1989   
2        1318  12/31/2008 0:00      1/3/1954        8/28/1989   
3        1318  12/31/2009 0:00      1/3/1954        8/28/1989   
4        1318  12/31/2010 0:00      1/3/1954        8/28/1989   

  terminationdate_key  age  length_of_service  city_name department_name  \
0            1/1/1900   52                 17  Vancouver       Executive   
1            1/1/1900   53                 18  Vancouver       Executive   
2            1/1/1900   54                 19  Vancouver       Executive   
3            1/1/1900   55                 20  Vancouver       Executive   
4            1/1/1900   56                 21  Vancouver       Executive   

  job_title  store_name gender_short gender_full termreason_desc  \
0       CEO          35            M        Male  Not Applicable   
1       CEO     

In [ ]:
a = [-12, 16]
b = [12, 9]

# Solution 1 using the mathematical forumla:
ab_math = (a[0] * b[0]) + (a[1] * b[1])

# This tells me that if it 0, the angle of these 2 vectors are completely perpendicular (90 degree)

0

In [ ]:
# Solution 2: using the dot function and making sure it is a numpy array type to use the .dot
ab = np.dot(a,b)
ab

0

2. Compute the Hadamard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [ ]:
#answer
ab = a * b
ab

array([[ 5, 12],
       [21, 32]])

In [ ]:
#desired output:
# np.array([[5,12],[21,32]])

3. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [ ]:
# Add two matrices using a nested loop

X = [[1,2,3],
    [4,5,6],
    [7,8,9]]

Y = [[2,3,7],
    [1,4,9],
    [3,2,3]]

In [ ]:
ans = np.array(X) + np.array(Y)
ans

array([[ 3,  5, 10],
       [ 5,  9, 15],
       [10, 10, 12]])

In [ ]:
#desired output:
#[[3,5,10],
# [5,9,15],
# [10,10,12]]

4. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [ ]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[7, 2, 4],
    [3, 9, 5],
    [8, 1, 6]]

# 3x4 matrix
Y = [[5,8,2,6],
    [1,4,9,3],
    [7,2,5,8]]

#X is 3 x 3, #Y is 3 x 4 matrix
#result of XY is 3 x 4 matrix.




In [ ]:
#answer:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[7, 2, 4],
    [3, 9, 5],
    [8, 1, 6]]

# 3x4 matrix
Y = [[5,8,2,6],
    [1,4,9,3],
    [7,2,5,8]]

#X is 3 x 3, #Y is 3 x 4 matrix
#result of XY is 3 x 4 matrix.



[[ 65  72  52  80]
 [ 59  70 112  85]
 [ 83  80  55  99]]


In [ ]:
# Answer:
# Matrix multiplication using @ operator or np.dot()
result = np.array(X) @ np.array(Y)
# Alternatively: result = np.dot(X, Y)

print(result)

[[ 65  72  52  80]
 [ 59  70 112  85]
 [ 83  80  55  99]]


In [ ]:
#desired output:
#[[65, 72, 52, 80],
# [59, 70, 112, 85],
# [83, 80, 55, 99]]

5. Compute the determinant of an n x n matrix.

Hint: Use
> np.linalg.det

In [ ]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [ ]:
#answer:
ans = np.linalg.det(matrix)
ans

17.999999999999996

6. Compute the inverse of an n x n matrix.

Hint: Use
> from numpy.linalg import inv

In [ ]:
a = np.array([[1., 2.], [3., 4.]])

In [ ]:
#answer:
from numpy.linalg import inv

ans = inv(a)
ans

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

7. (Application)
Three customers made the following purchases of three different items at an office supply store:
* Customer W bought 2 notebooks, 4 pens and 3 staplers for \$38.80
* Customer X bought 3 notebooks, 3 pens and 2 staplers for \$32.00
* Customer Y bought 4 notebooks, 8 pens and 1 stapler for \$36.60

Based on this, how much did customer Z spend in buying 1 notebook, 2 pens and 4 staplers?

In [ ]:
# answer
import numpy as np

# Coefficient matrix (items)
A = np.array([
    [2, 4, 3],  # W
    [3, 3, 2],  # X
    [4, 8, 1]   # Y
])

# Total cost vector
B = np.array([38.80, 32.00, 36.60])

# Solve for [notebook, pen, stapler]
prices = np.linalg.solve(A, B)

# Print individual item prices
notebook, pen, stapler = prices
print(f"Notebook: ${notebook:.2f}, Pen: ${pen:.2f}, Stapler: ${stapler:.2f}")

# Calculate Customer Z's cost (1 notebook, 2 pens, 4 staplers)
Z_total = 1 * notebook + 2 * pen + 4 * stapler
print(f"Customer Z spent: ${Z_total:.2f}")


Notebook: $3.30, Pen: $1.90, Stapler: $8.20
Customer Z spent: $39.90




---



---



> > > > > > > > > © 2025 Institute of Data


---



---



